apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: employees-database-pv-claim
  labels:
    app: employees
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi